import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '@/components/Nav'
import Footer from "@/components/Footer";
import Shopping from "@/components/Shopping";
import CartProvider from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <CartProvider >
         <nav>
          <Nav />
        </nav>
        <Shopping />
        <main>
         {children} 
        </main>
         </CartProvider>
        <footer className="mt-[4rem]">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
